site_name: Coding Projects in C
site_description: Projects in C from 2020
site_author: Krithika Chockalingam
site_url: https://kc-19.github.io/Coding-Projects-in-C/

repo_name: Coding-Projects-in-C
repo_url: https://github.com/kc-19

theme: 
  name: 'material'
  
static_templates: 
  - 404.html
  
include_search_page: false
search_index_only: true

language: en
palette: 
  scheme: default
  primary: pink
  accent: black
font: 
  text: Google Sans
  code: Regular
favicon: assets/favicon.png
icon: 
  logo: logo
  
extra: 
  social: 
    - icon: fontawesome/brands/github
      link: https://github.com/kc-19/Coding-Projects-in-C
